language: c

dist: xenial

compiler:
  - gcc
  - clang

jobs:
  include:
  - dist: focal
    compiler: gcc
  - dist: focal
    compiler: clang

addons:
  apt:
    packages:
      - libncursesw5-dev
      - check

script:
  - make
  - make test

