#!/bin/sh

if [ ! "x$FILES_FOREGROUND" = "xyes" ] && [ ! "x$DISPLAY" = "x" ] && [ "$RUNNING_IN_XTERM" != t ] ; then
        RUNNING_IN_XTERM=t exec xterm -title `basename $0` -e "$0 $*"
fi

if [ ! -e "$1"/clipboard_list ]; then
	rm -rf "$1"
	exit 0;
fi

if [ `cat "$1"/clipboard_path` = `cat "$1"/cwd` ]; then
	rm -rf "$1"
	exit 0;
fi

xargs -0 -a "$1"/clipboard_list -I '{}' mv -vi `cat "$1"/clipboard_path`/{} .

rm -rf "$1"
