#!/bin/sh

source `dirname $0`/xterminal "$@"

if [ ! -e "$1"/clipboard_list ]; then
	rm -rf "$1"
	exit 0;
fi

if [ "`cat \"$1\"/clipboard_path`" = "`cat \"$1\"/cwd`" ]; then
	rm -rf "$1"
	exit 0;
fi

xargs -0 -a "$1"/clipboard_list -I '{}' mv -vi "`cat \"$1\"/clipboard_path`/{}" .

rm -rf "$1"
