#!/bin/sh

. `dirname $0`/xterminal "$@"

if [ ! -e "$1"/clipboard_list ]; then
	exit 0;
fi

if [ "`cat \"$1\"/clipboard_path`" = "`cat \"$1\"/cwd`" ]; then
	exit 0;
fi

exec xargs -0 -a "$1"/clipboard_list -I '{}' mv -vi "`cat \"$1\"/clipboard_path`/{}" .
