#!/bin/sh

if [ ! "x$DFM_FOREGROUND" = "xyes" ] && [ ! "x$DISPLAY" = "x" ] && [ "$RUNNING_IN_XTERM" != t ] ; then
	RUNNING_IN_XTERM=t exec xterm -title `basename $0` -e "$0 $*" < /dev/null > /dev/null 2> /dev/null
	#RUNNING_IN_XTERM=t exec urxvt -e "$0" "$*" < /dev/null > /dev/null 2> /dev/null
	exit 0
fi

unset RUNNING_IN_XTERM
