#!/bin/sh

if [ "$RUNNING_IN_XTERM" != t ] ; then
        RUNNING_IN_XTERM=t exec xterm -title `basename $0` -e "$0 $*"
fi

if [ -e "$1"/marked ]; then
	xargs -0 -a "$1"/marked rm -rvfI
else
	rm -rvfI "`cat $1/selected`"
fi

rm -rf "$1"
