#!/bin/sh
archivename=`basename "$1"`
mountdir=`mktemp -d -p "" "$archivename.XXXXXX"`

echo Opening "$1"
if file -b --mime-type "$1"|grep 'application/.*rar'; then
	rar2fs "$1" "$mountdir"
else
	archivemount -o readonly "$1" "$mountdir"
fi

cd "$mountdir"
dfm
cd /

fusermount -u "$mountdir"
rmdir "$mountdir"
